#!/usr/bin/env bash
# Pre-commit guard: refuse to commit anything under content/ except the
# hand-maintained landing page and static assets. content/ is regenerated
# from the (private) Obsidian vault by `npm run sync` and must never be
# checked into the public repo.
#
# Install once with:
#   ln -sf ../../scripts/pre-commit-guard.sh .git/hooks/pre-commit
set -euo pipefail

allowed_re='^content/(index\.md|_static/.*)$'

staged=$(git diff --cached --name-only --diff-filter=ACM | grep -E '^content/' || true)

blocked=()
while IFS= read -r f; do
  [ -z "$f" ] && continue
  if ! [[ "$f" =~ $allowed_re ]]; then
    blocked+=("$f")
  fi
done <<< "$staged"

if [ ${#blocked[@]} -gt 0 ]; then
  echo "✋ pre-commit-guard: refusing to commit synced vault content."
  echo "   These files are regenerated by 'npm run sync' from the private vault"
  echo "   and must never be tracked in this repo:"
  for f in "${blocked[@]}"; do
    echo "     - $f"
  done
  echo
  echo "   To unstage:  git restore --staged content/"
  echo "   Only content/index.md and content/_static/** may be committed."
  exit 1
fi
